f = GAF.GameAssetFactory()
gae = GAC.EnemyCreator()
gap = GAC.PlayerCreator()
gawt = GAC.WorldTerrainCreator()
f:Register("E",gae)
f:Register("P",gap)
f:Register("WT",gawt)
a = f:Create("E")
b = f:Create("P")
c = f:Create("WT")